CREATE TABLE properties (
    id BIGINT NOT NULL AUTO_INCREMENT,
    property_identity_hash CHAR(64) NOT NULL,
    region_code CHAR(10) NOT NULL COMMENT '동 단위 법정동 코드',
    region_name VARCHAR(100) NOT NULL,
    sigungu VARCHAR(100) NOT NULL,
    property_name VARCHAR(200) NULL,
    property_type VARCHAR(30) NULL,
    lot_number VARCHAR(50) NULL,
    main_number VARCHAR(10) NULL,
    sub_number VARCHAR(10) NULL,
    road_name VARCHAR(200) NULL,
    built_year SMALLINT NULL,
    min_exclusive_area DECIMAL(12, 4) NULL,
    max_exclusive_area DECIMAL(12, 4) NULL,
    min_contract_area DECIMAL(12, 4) NULL,
    max_contract_area DECIMAL(12, 4) NULL,
    min_deposit_amount BIGINT NULL COMMENT '만원 단위',
    max_deposit_amount BIGINT NULL COMMENT '만원 단위',
    min_monthly_rent_amount BIGINT NULL COMMENT '만원 단위',
    max_monthly_rent_amount BIGINT NULL COMMENT '만원 단위',
    min_trade_amount BIGINT NULL COMMENT '만원 단위',
    max_trade_amount BIGINT NULL COMMENT '만원 단위',
    first_contract_date DATE NULL,
    latest_contract_date DATE NULL,
    trade_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_properties_identity_hash (property_identity_hash),
    KEY idx_properties_region_code (region_code),
    KEY idx_properties_region_type (region_code, property_type),
    KEY idx_properties_name (property_name),
    CONSTRAINT fk_properties_region_code
        FOREIGN KEY (region_code) REFERENCES legal_dongs (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
