CREATE TABLE real_estate_trades (
    id BIGINT NOT NULL AUTO_INCREMENT,
    trade_hash CHAR(64) NOT NULL,
    source_file VARCHAR(255) NULL,
    no_in_file INT NULL,
    sigungu VARCHAR(100) NOT NULL,
    lot_number VARCHAR(50) NULL,
    main_number VARCHAR(10) NULL,
    sub_number VARCHAR(10) NULL,
    property_name VARCHAR(200) NULL,
    property_type VARCHAR(30) NULL,
    road_condition VARCHAR(30) NULL,
    rent_type VARCHAR(10) NULL,
    exclusive_area DECIMAL(12, 4) NULL,
    contract_area DECIMAL(12, 4) NULL,
    contract_year_month CHAR(6) NOT NULL,
    contract_day TINYINT NULL,
    contract_date DATE NOT NULL,
    deposit_amount BIGINT NULL COMMENT '만원 단위',
    monthly_rent_amount BIGINT NULL COMMENT '만원 단위',
    trade_amount BIGINT NULL COMMENT '매매 거래금액, 만원 단위',
    floor INT NULL,
    built_year SMALLINT NULL,
    road_name VARCHAR(200) NULL,
    canceled_date DATE NULL,
    deal_type VARCHAR(30) NULL,
    broker_location VARCHAR(100) NULL,
    registration_date DATE NULL,
    apartment_dong_name VARCHAR(100) NULL,
    buyer VARCHAR(50) NULL,
    seller VARCHAR(50) NULL,
    contract_period VARCHAR(20) NULL,
    contract_type VARCHAR(20) NULL,
    renewal_request_right VARCHAR(20) NULL,
    previous_deposit_amount BIGINT NULL COMMENT '만원 단위',
    previous_monthly_rent_amount BIGINT NULL COMMENT '만원 단위',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_real_estate_trades_hash (trade_hash),
    KEY idx_real_estate_trades_region_date (sigungu, contract_date),
    KEY idx_real_estate_trades_property (property_type, rent_type),
    KEY idx_real_estate_trades_road_name (road_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
